### ISSUE TITLE
How to define element with multiple sub elements?

### ISSUE THREAD

**Issue by jakestrouse00** [cercide/fastapi-xml#13]
Hi,

I am trying to define an element that contains multiple sub-elements (some of the sub-elements also contain multiple sub-elements). The XML I am aiming for looks like this:
```xml
<Query latencySensitive="true">
  <Checkin>2017-06-07</Checkin>
  <Nights>5</Nights>
  <DeadlineMs>500</DeadlineMs>
  <PropertyList>
    <Property>8675309</Property>
  </PropertyList>
  <Context>
    <Occupancy>4</Occupancy>
    <OccupancyDetails>
      <NumAdults>2</NumAdults>
      <Children>
        <Child age="4"/>
        <Child age="12"/>
      </Children>
    </OccupancyDetails>
    <UserCountry>US</UserCountry>
    <UserDevice>mobile</UserDevice>
  </Context>
</Query>
```

This is currently what I have written, but when submitting a request I get a 400, Bad Request with the response: `{
  "detail": "There was an error parsing the body"
}`

```python
@dataclass
class Query:
    checkin: str = field(
        metadata={"examples": ["2025-08-10"], "name": "Checkin", "type": "Element"}
    )
    nights: int = field(metadata={"examples": [3], "name": "Nights", "type": "Element"})
    property_list: List[str] = field(
        metadata={
            "wrapper": "PropertyList",
            "name": "Property",
            "type": "Element",
            "examples": [["64a58668992086b9bb75d6fa"]],
        }
    )
# everything above this works, but context is breaking it
    context: List[int | str | str] = field(
         metadata={
             "wrapper": "Context",
             "type": "Elements",
             "name": "rere",
             "choices": (
                 {"name": "Occupancy", "type": "Element", "examples": [2]},
                 {"name": "UserCountry", "type": "Element", "examples": ["GB"]},
                 {"name": "UserDevice", "type": "Element", "examples": ["Desktop"]}
             )
         }
     )
     ```

Any help would be greatly appreciated

**Comment by cercide** [comment]
Hey there,

I’ve briefly reviewed the code you provided, and there are a few points that need your attention.

## Unknown XML Element

The code is referencing a tag named `rere`, which is not part of the given example.

## Type Declaration Mismatch

The type for `context` is declared as `List[int | str | str]`, but the actual sub-elements for each choice are of type `Element`. This discrepancy needs to be addressed.

If you’re still encountering issues after resolving the above, you may want to reconsider the object’s structure as described in the following point.

## Confusing XML Structure

I found the contextual data challenging to follow. It seems that using a context object with optional attributes would provide guest information more intuitively, rather than relying on checking the object type. Why do I bring this up? First, determining what data was provided this way seems unconventional. And second, the main reason:

I hadn’t considered the option of wrapping the type `Elements`. It could work, but my original intention for the wrapper argument was to handle structures like this:

```
<Context>
  <rere>...</rere>
  <rere>...</rere>
  <rere>...</rere>
</Context>
```

**Comment by jakestrouse00** [comment]
### Unknown XML Element
My apologies for the "name": "rere" part. It was left over from testing. The name should be "Context." 

### Type Declaration Mismatch
As to the Type Declaration Mismatch, how would I go about implementing that? For example, I am unsure where to import `Element` from 
### Confusing XML Structure
Unfortunately, I don't have control over the format of the guest XML data, so I have to match the formatting Google sends to me.
Just for some context, here is the documentation I am working off of: [DOCS](https://developers.google.com/hotels/hotel-prices/dev-guide/query-messages#live_pricing_query_example)

**Comment by cercide** [comment]
Thank you for the clarification. This effectively resolves the first issue. Additionally, it seems to me that the second and third issues are actually the same. The type declaration isn’t a mismatch and should work in other scenarios (though not in yours). I apologize for not explaining that clearly earlier.

A good approach for debugging what’s really going wrong is to ensure that your model specification matches the input data. Testing with sample data can provide more detailed insights. XSDATA provides some parsing examples [here](https://xsdata.readthedocs.io/en/latest/data_binding/xml_parsing/). Any suggestions on how to generate more meaningful error messages would be greatly appreciated.

Based on the information you provided, it appears that the context specification doesn't align with the expected data format. I found the context specifications [here](https://developers.google.com/hotels/hotel-prices/xml-reference/queries#Context). According to the documentation:

- The Context field is an object with specific properties.
- A query must include a context object.
- Multiple context objects can be part of a single query.

Therefore, your implementation should resemble something like this:

```python
class Context:
    ...

class Query:
    ...
    context: List[Context] = field(
        metadata={"type": "Element"}
    )
```
